### ISSUE TITLE
Use "payload.getCodeName(code)" only for saving memory.

### ISSUE THREAD

**Issue by Zeppelin500** [HWHardsoft/emonMbus#3]
If you use ````payload.getCodeName(code)````, you will get only the string from the coding table like **external_temperature**. 
But if you use ````const char* name = root[i]["name"]````, you will get additional the information of the function field. (min, max, err) and the output is **external_temperature_min**.

Maybe I should describe the library documentation better.

**Comment by HWHardsoft** [comment]
Done!
